### ISSUE TITLE
Google changed one of my two thermostats. No longer shows up with getDevices

### ISSUE THREAD

**Issue by Sal-Tepedino** [gboudreau/nest-api#135]
A week ago, one of my two thermostats stopped reporting data. Investigating showed that it seems to be gone when querying with
var_dump($nest->getDevices());
Which lists just one.
When selecting the thermostats on the Nest website, one is shown as /thermostat/SERIALNUMBER while the other shows as /thermostat/DEVICE_HEXADECIMAL where the Hex number is not that device's serial number. Attempting to replace the serial with the DEVICE_number didn't work.

**Comment by bauzer714** [comment]
@Sal-Tepedino - Unfortunately mine is still using serial so I don't have live data to work with. Can you open Chrome Developer tools and go to the "Network" tab,  Type "app_launch" into the top left search box and then expand "updated_buckets" once it updates?  The code requires that the keys have a period in them, which is what is used to split to get the device serial.  I'm curious what they updated it to.

![image](https://user-images.githubusercontent.com/13224936/105769048-39a0bd00-5f2b-11eb-96d7-fe3d0a05407d.png)

**Comment by Sal-Tepedino** [comment]
It only seems to show one of the devices. Both are shown on the page,
though.

**Comment by bauzer714** [comment]
I'm going to need you to provide more detail. A screenshot similar to the one I provided would be helpful. Otherwise we'll have to wait for a contributor who has their devices updated and update the code.

**Comment by zecanard** [comment]
Please see https://github.com/gboudreau/nest-api/issues/115#issuecomment-596142188. I faced this exact issue last year, and the solution was to reset the Works With Nest connection.

Note that this will erase your thermostat’s history associated to your home, unfortunately.

**Comment by bauzer714** [comment]
Thanks @zecanard - this seems like a pain. Hopefully it doesn't occur very often.

**Comment by Sal-Tepedino** [comment]
That did it. It's back to using the serial number instead of the device ID.
What's that all about? It just randomly changed one day.

Thanks!

**Comment by knappster1** [comment]
I know this issue is closed, but the last time my hourly script worked was at 10 pm central time on Feb 5, so it leads me to believe that around 12 am on Feb 6 that something changed for me.  I don't know what the URL used to be, but it is DEVICE_HEX for me at the moment.  I only have one nest device, which is the thermostat and I already migrated to google about a year ago, so it is slightly different than @Sal-Tepedino and @zecanard but I've verified the issueToken and cookies are correct multiple times.

**Comment by Sal-Tepedino** [comment]
If when you view the thermostat on Nest's page the URL has 'DEVICE_IDHERE',
where it's the device ID and not the serial, that's what happened to me.
After I fixed it on one thermostat, it happened on the other one. The only
fix I've found is:
Remove the thermostat from the Nest App, then in the thermostat's
interface, 'Reset WWN connection' (the exact place this is escapes me, but
it's not hard to find). Then re-add the thermostat in the nest app, just
like it was a new device.

Not an elegant solution, but it works.

**Comment by zecanard** [comment]
Then this answers the question as to whether this issue can affect Google accounts as well. I had a suspicion that it could, but so far we’d only seen it on legacy Nest accounts. I really have no idea what causes it. It just happens out of the blue for a handful of people.

**Comment by Sal-Tepedino** [comment]
My account is a Google Account. I migrated it ... last year I think.

**Comment by knappster1** [comment]
@Sal-Tepedino yes, the URL is: https://home.nest.com/thermostat/DEVICE_ (followed by 16 hex characters).  When I use the script I get an undefined offset: 0 on line 999 of the current nest.class.php file (followed by a slew of other errors).  I did a var_dump on $status just after line 1095 and it definitely has my account information, so I am sure that it is able to access my account, but I'm really not sure how to parse the data otherwise.  I'm not ready to say that resetting WWN will fix it, but I intend to try this evening and report back.
By the way, I saw the WWN reset last night by going to the thermostat, settings, reset, and scrolling down.  I almost tried it last night, but there was lengthy warning and I thought I would sleep on it first.

**Comment by zecanard** [comment]
@Sal-Tepedino Ah, my mistake for assuming 🙃

**Comment by Sal-Tepedino** [comment]
It sounds daunting with their warning, but there's nothing to it. You
delete it from your app, reset WWN, then re-add it to the app. Takes a few
minutes and it starts showing up in the var dump again.

**Comment by knappster1** [comment]
Reset WWN and everything is back to normal now.  Thanks for sharing your experiences and helping to resolve this.  The navigation was:
Settings (gear icon)
Reset
WWN Connection

**Comment by sparky672** [comment]
> Please see [#115 (comment)](https://github.com/gboudreau/nest-api/issues/115#issuecomment-596142188). I faced this exact issue last year, and the solution was to reset the Works With Nest connection.
> 
> Note that this will erase your thermostat’s history associated to your home, unfortunately.

I went through this procedure as detailed in the 115 comment.  Deleted from the account, reset the WWN, and added it back to the account.  From what I am seeing, none of my history data was lost.
