### ISSUE TITLE
Get last_connection Time UTC Issue

### ISSUE THREAD

**Issue by rossking** [gboudreau/nest-api#46]
I am using this Class to archive Thermostat info.

One of the issues from the last year was dealing with DST and causing dates to be messed up.

So I have switched to using UTC for all time stamps and will do conversion to Local time at DataDump.

However I am not sure of how to reliably convert your time. From the code below it looks like you take a UNIX timestamp value from NEST and have PHP convert to local time.

I still want to leave a time zone on PHP so I can use functions to adjust the output.

Question #1 - Is the `$connection_info->last_connection` straight from NEST and is it UTC with no adjustments?
Question #2 - Do you know of a better way to get UTC other than modifying your code as I have done below and adding a UTC time? 

Is this something that I can add to your code (or should I keep outside on my own fork)

```
 private function getDeviceNetworkInfo($serial_number=null) {
        $this->getStatus();
        $serial_number = $this->getDefaultSerial($serial_number);
        $connection_info = $this->last_status->track->{$serial_number};
        return (object) array(
            'online' => $connection_info->online,
            'last_connection' => date('Y-m-d H:i:s', $connection_info->last_connection/1000),
            'last_connection_UTC' => gmdate("Y-m-d H:i:s", $connection_info->last_connection/1000),
            'wan_ip' => @$connection_info->last_ip,
            'local_ip' => $this->last_status->device->{$serial_number}->local_ip,
            'mac_address' => $this->last_status->device->{$serial_number}->mac_address
        );
    }
```

**Comment by gboudreau** [comment]
1. Yes, `$connection_info->last_connection` is from Nest. It's a timestamp, thus by definition, it is the number of seconds (or ms in this case) since Jan. 1 1970 UTC.

2. The best way to handle this is to either convert the date as you save it in your database, or tell your PHP script that you want all dates as UTC:
```
    date_default_timezone_set('UTC');
```
Just execute that before at the beginning of your script, and all dates you'll get will be in UTC.
In fact, my examples.php script contains that: https://github.com/gboudreau/nest-api/blob/master/examples.php#L11
