### ISSUE TITLE
Multiple Homes

### ISSUE THREAD

**Issue by seesoe** [gboudreau/nest-api#70]
Is it possible to query devices in a different home that's on the account? I have 2 devices from the first default home and 4 devices at the second home, but i can't access the devices at the second home.

**Comment by gboudreau** [comment]
It shouldn't be a problem.
The `getStatus()` function just sends the user ID in the request, so it should receive all information, for all homes and all devices in those homes.

Does `getUserLocations()` return both homes? I think it should.
How about `getDevices()`, does it return all devices, or (most likely) just the one from your default home?
If the later, try to change the `getDevices()` to this:

```php
    public function getDevices($type=DEVICE_TYPE_THERMOSTAT) {
        $this->prepareForGet();
        if ($type == DEVICE_TYPE_PROTECT) {
            $protects = array();
            $topaz = isset($this->last_status->topaz) ? $this->last_status->topaz : array();
            foreach ($topaz as $protect) {
                $protects[] = $protect->serial_number;
            }
            return $protects;
        }
        $devices_serials = array();
        foreach ($this->last_status->user->{$this->userid}->structures as $structure) {
            list(, $structure_id) = explode('.', $structure);
            foreach ($this->last_status->structure->{$structure_id}->devices as $device) {
                list(, $device_serial) = explode('.', $device);
                $devices_serials[] = $device_serial;
            }
        }
        return $devices_serials;
    }
```

**Comment by J-Prince** [comment]
I have 2 homes with one Nest thermostat each. 

I too noticed that the getDevices() only returns the devices in the first home. The code you suggested for that function works well and returns the devices in both locations. Will you merge that change to the repository? 

Also, I noticed a problem with turnOff. It always uses the default serial, even when one is provided in parameter. I think it's because when passing a serial number, it's received in the $temperature variable of setTargetTemperatureMode() instead of $serial_number. 

It could be changed from: 

`    public function turnOff($serial_number=null) {
        return $this->setTargetTemperatureMode(TARGET_TEMP_MODE_OFF, $serial_number);
    }`

To:

`public function turnOff($serial_number=null) {
        return $this->setTargetTemperatureMode(TARGET_TEMP_MODE_OFF, 0, $serial_number);
    }`
