### ISSUE TITLE
sinds nest firmware update AWAY_MODE doesnt function anymore

### ISSUE THREAD

**Issue by djalexnl** [gboudreau/nest-api#72]
Sinds the latest firmware update, nest changed several settings and now uses eco mode. 
can you update the code so we can use this mode?

heat or eco or off

thanks in advance

**Comment by gboudreau** [comment]
Away mode is still available in both the Nest mobile and web apps.
Starting and exiting away mode works fine too:
```
$nest->setAway(AWAY_MODE_ON);
$nest->setAway(AWAY_MODE_OFF);
```

Also, `setAwayTemperatures()` works fine to change what they now call Eco temperatures.

I don't see an "Eco mode" anywhere, on my thermostat, or in the web-app, or mobile app.
From what I read from their communications, they only renamed away temperatures to eco temperatures, and the thermostat should now display ECO mode instead of Auto-away when in away mode, but the functionality didn't change, and no code change is required.

**Comment by djalexnl** [comment]
Hi, first of all thank you for the code, i use this in my home automation system for more then a year now.  

Second of all you are right, they changed the away mode to Eco the rest remained the same. 

But here is the isue if have sinds a couple of days. If i go to sleep my home automation system puts the thermostat in the away_mode_on. (now it turns on the eco mode). But if i walk past the thermostat or the thermostat  detects a pet, the heating turns on, even though i have disabled the sensors from both my nest thermostat and nest protect and geographic detection in the app. This never happend before, and is after the firmware update.

So i disabled autoaway in the app, but then i figured out you cannot put the thermostat in the eco / away mode using the api. I can turn the heating off and on but not in the eco mode using the api when autoaway is disabled.

Solution for now is to set the thermostat to away, and after it is set in the eco mode, then turn of the autoway mode by api, so it doesnt detect anything no more. Then when i want to turn it on by api, enable autoway and and set the awaymode to off.

Hopefully this wil help other people who also find out the heating system suddenly turns on at night.

Again thanks for the code!

**Comment by gboudreau** [comment]
Quick note: I have just added a setter to force ECO mode.
It is called automatically when you change Away mode, because that was what was happening before.

Before:
- auto away > away temperatures are used
- manual away > away temperatures are used
After:
- auto away > ECO temperatures are used
- manual away > ECO temperatures are NOT used

So when you change the away mode using setAway(), I will also at the same time change the thermostat to use ECO temperatures (or not, when turning off away mode).
