### ISSUE TITLE
Documentation in examples.php to Set Humidity (on, off, %)

### ISSUE THREAD

**Issue by jocamero** [gboudreau/nest-api#83]
Hello,

I see in the 'Setters' section of readme.md that Humidity (on, off, %) is an option but I'm not seeing anything in the documentation on how to set this.  It would be great to have an example for how to set the humidity or turn the humidifier on/off.

For example, I'd like to have a script run that will check the outside temperature and disable the humidifier or set the level of humidification based on the outside temp (dew point would be even better!).

**Comment by gboudreau** [comment]
```
$nest->enableHumidifier(true); // Enable or disable Nest Sense Humidifier
$nest->setHumidity(40);
```

**Comment by rr0ss0rr** [comment]
Take a look at https://github.com/rbrenton/nest-utils.git
It contains nest-humidityCheck.php that will do what you want

**Comment by jocamero** [comment]
Thanks guys!

**Comment by rr0ss0rr** [comment]
NP .. It worked well over the winter .. I cleaned up the display a little (added timestamp and rounded temps to whole numbers and added it to cron to run every 20 minutes and appended the output to a file so that I have a history.

2017-05-26 19:13  THERMOSTAT(temp=68F, dewpoint=52F, humidity=57%, target=10%) - OUTSIDE(temp=60F, dewpoint=59F, humidity=98%) - OK
